### PR TITLE
Chinese translate for Warframe hud

### PR DESCRIPTION
**Pull request by DoctorKoKoDaYo**
I have a question in translate ,follow the english.txt	
`hud_pickup_flamethrower_ammo" : "Minigun Ammo",` seems meaning flame thrower's ammo but it was "minigun ammo" in text
,so I translated it to flame thrower ammo.
[chinese(WFhud).txt](https://github.com/segabl/pd2-warframe-hud/files/8033315/chinese.WFhud.txt)

### CODE REVIEW

**Comment by segabl** [comment]
Oh yeah that's a mistake on my part, good you caught it

**Comment by DoctorKoKoDaYo** [comment]
The Biker Heist's Mechanic hasn't text to be translate, could you add it?

If you can add it , its translate is "机械师"

**Comment by segabl** [comment]
what exactly?

**Comment by DoctorKoKoDaYo** [comment]
As the screenshot shows

**Comment by segabl** [comment]
oh, you can just add a translation key for "hud_sub_name_mch"

**Comment by DoctorKoKoDaYo** [comment]
thanks

**Comment by DoctorKoKoDaYo** [comment]
New translate:
`"hud_sub_name_xuk" : "迅康"`

**Comment by DoctorKoKoDaYo** [comment]
new translate:
```
	"menu_wfhud" : "Warframe HUD",
	"menu_wfhud_desc" : "调整星际战甲HUD的设置",
	"menu_wfhud_hud_scale" : "HUD缩放比例",
	"menu_wfhud_hud_scale_desc" : "调整HUD中所有组件元素的缩放倍数\n重启劫案以应用更改",
	"menu_wfhud_font_scale" : "字体显示大小",
	"menu_wfhud_font_scale_desc" : "调整游戏中显示字体的缩放倍数，此缩放倍数会与HUD缩放比例倍数相乘\n重启劫案以应用更改",
	"menu_wfhud_vanilla_ammo" : "原版弹药显示",
	"menu_wfhud_vanilla_ammo_desc" : "按照原版弹药显示风格，在总弹量中计算已经被装填在弹匣中的弹药",

         "hud_pickup_money" : "美元",
```

**Comment by segabl** [comment]
here's the next batch of strings coming in:
```

	"hud_action_attaching_magnet" : "Attaching magnet",
	"hud_action_fixing_saw" : "Fixing saw",
	"hud_action_placing_saw" : "Placing saw",
	"hud_action_plugging_in_power" : "Plugging in power",
	"hud_action_rebooting_device" : "Rebooting device",
	"hud_action_picking_up_c4" : "Picking up C4",
	"hud_action_defusing_c4" : "Defusing C4",
	"hud_action_opening_register" : "Opening cash register",
	"hud_action_fixing_cutter" : "Fixing cutter",
	"hud_action_closing_door" : "Closing door",
	"hud_action_entering_vehicle" : "Entering vehicle",
	"hud_action_starting_forklift" : "Starting forklift",
	"hud_action_pouring_gasoline" : "Pouring gasoline",
	"hud_action_opening_briefcase" : "Opening briefcase",
	"hud_action_setting_up_device" : "Setting up device",
	"hud_action_getting_on_bike" : "Getting on bike",
	"hud_action_searching_for_tools" : "Searching for tools",
	"hud_action_taking_soda" : "Taking soda",
	"hud_action_taking_bike_part" : "Taking bike part",
	"hud_action_untying" : "Untying",
	"hud_action_charging_laser" : "Charging laser",
	"hud_action_placing_sentry_gun" : "Placing sentry gun",
	"hud_action_stashing_vial" : "Stashing vial",
	"hud_action_pulling_hose" : "Pulling hose",
	"hud_action_closing" : "Closing",
	"hud_action_starting_override" : "Starting override",
	"hud_action_erasing_footage" : "Erasing footage",
	"hud_action_applying_tape" : "Applying tape",
	"hud_action_picking_up_plates" : "Picking up printing plates",
	"hud_action_dropping_bag" : "Dropping bag",
	"hud_action_adding_saw_blade" : "Adding saw blade",
	"hud_action_moving_shelf" : "Moving bookshelf",
	"hud_action_placing_thermite" : "Placing Thermite",
	"hud_action_searching_for_usb" : "Searching for USB stick",
	"hud_action_turning_on_water" : "Turning on water",```

**Comment by DoctorKoKoDaYo** [comment]
"menu_wfhud_margin_h" : "水平边距",
	"menu_wfhud_margin_h_desc" : "调整HUD中所有组件元素与屏幕左右的水平距离\n重启劫案以应用更改",
	"menu_wfhud_margin_v" : "垂直边距",
	"menu_wfhud_margin_v_desc" : "调整HUD中所有组件元素与屏幕上下的垂直距离\n重启劫案以应用更改",
	"menu_wfhud_rare_mission_equipment" : "稀有任务装备",
	"menu_wfhud_rare_mission_equipment_desc" : "获得任务装备时显示稀有资源掉落提示",
	"menu_wfhud_health_labels" : "浮动血条",
	"menu_wfhud_health_labels_desc" : "瞄准角色时在其头顶显示浮动生命条",
	"menu_wfhud_show_downs" : "倒地计数",
	"menu_wfhud_show_downs_desc" : "在BUFF栏和队友装备栏中显示倒地计数器",
	"hud_action_adding_saw_blade" : "添加锯片中",
	"hud_action_applying_tape" : "使用胶带中",
	"hud_action_attaching_magnet" : "挂载磁铁中",
	"hud_action_charging_laser" : "充能镭射中",
	"hud_action_closing_door" : "关门中",
	"hud_action_closing" : "关闭中",
	"hud_action_defusing_c4" : "拆除C4中",
	"hud_action_dropping_bag" : "放下包中",
	"hud_action_entering_vehicle" : "进入载具中",
	"hud_action_erasing_footage" : "抹除数据中",
	"hud_action_fixing_cutter" : "修理切割器中",
	"hud_action_fixing_saw" : "修理电锯中",
	"hud_action_getting_on_bike" : "上摩托车中",
	"hud_action_moving_shelf" : "移动书架中",
	"hud_action_opening_briefcase" : "打开公文包中",
	"hud_action_opening_register" : "打开收银机中",
	"hud_action_picking_up_c4" : "拾起C4中",
	"hud_action_picking_up_plates" : "拾取模板中",
	"hud_action_placing_saw" : "放置电锯中",
	"hud_action_placing_sentry_gun" : "放置哨戒机枪中",
	"hud_action_placing_thermite" : "放置铝热剂中",
	"hud_action_plugging_in_power" : "插入电源中",
	"hud_action_pouring_gasoline" : "泼洒汽油中",
	"hud_action_pulling_hose" : "拉动水管中",
	"hud_action_rebooting_device" : "重启设备中",
	"hud_action_searching_for_tools" : "搜寻工具中",
	"hud_action_searching_for_usb" : "搜索U盘中",
	"hud_action_setting_up_device" : "放置设备中",
	"hud_action_starting_forklift" : "启动叉车中",
	"hud_action_starting_override" : "启动过载中",
	"hud_action_stashing_vial" : "放置样本中",
	"hud_action_taking_bike_part" : "拆解摩托中",
	"hud_action_taking_soda" : "拿苏打水中",
	"hud_action_turning_on_water" : "打开水源中",
	"hud_action_untying" : "解绑中",

**Comment by DoctorKoKoDaYo** [comment]
new translate
`"menu_wfhud_custom_chat" : "自定义聊天",
"menu_wfhud_custom_chat_desc" : "用模组的聊天栏替换原版游戏聊天栏",
"hud_chat_send_message" : "向队员发送消息",`

**Comment by segabl** [comment]
> new translate `"menu_wfhud_custom_chat" : "自定义聊天", "menu_wfhud_custom_chat_desc" : "用模组的聊天栏替换原版游戏聊天栏", "hud_chat_send_message" : "向队员发送消息",`

hey, I have added new text. to make translating easier for us both, you can go directly to the chinese language file on the dev branch: https://github.com/segabl/pd2-warframe-hud/blob/dev/loc/schinese.txt
click the edit button there, then you can make changes and it will send a request for them to be integrated

**Comment by DoctorKoKoDaYo** [comment]
> 
When I open the branch, page was tip this :
You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork DoctorKoKoDaYo/pd2-warframe-hud, so you can send a pull request.

**Comment by segabl** [comment]
> > 
> 
> When I open the branch, page was tip this : You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork DoctorKoKoDaYo/pd2-warframe-hud, so you can send a pull request.

yes, that is exactly how it is supposed to be done :)

**Pull request merged**
